import { defineSlotRecipe } from '@pandacss/dev';

export const dialog = defineSlotRecipe({
  className: 'dialog',
  description: 'Native dialog overlay with header, body, and footer slots',
  slots: ['root', 'header', 'body', 'footer', 'title', 'close'],
  base: {
    root: {
      // Panda preflight sets margin: 0, which removes UA dialog centering.
      position: 'fixed',
      inset: '0',
      margin: 'auto',
      height: 'fit-content',
      width: 'calc(100% - 2rem)',
      maxWidth: '28rem',
      maxHeight: 'calc(100% - 2rem)',
      overflow: 'auto',
      p: 'md',
      borderWidth: '1px',
      borderStyle: 'solid',
      borderColor: 'neutral.700',
      borderRadius: 'lg',
      backgroundColor: 'surface',
      color: 'text',
      boxShadow: 'elevated',
      _light: {
        borderColor: 'border',
        boxShadow: 'lg',
      },
      '&::backdrop': {
        backgroundColor: 'oklch(0% 0 0 / 0.55)',
      },
    },
    header: {
      display: 'flex',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: 'sm',
      mb: 'md',
    },
    title: {
      fontFamily: 'sans',
      fontWeight: 'bold',
      fontSize: 'lg',
      lineHeight: 'tight',
      m: 0,
    },
    body: {
      fontFamily: 'sans',
      fontSize: 'md',
      lineHeight: 'normal',
    },
    footer: {
      display: 'flex',
      flexWrap: 'wrap',
      justifyContent: 'flex-end',
      alignItems: 'center',
      gap: 'sm',
      mt: 'md',
      '& > *': {
        width: 'auto',
        flex: '0 1 auto',
      },
    },
    close: {
      appearance: 'none',
      border: 'none',
      background: 'transparent',
      color: 'muted',
      cursor: 'pointer',
      fontSize: 'xl',
      lineHeight: '1',
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      minW: '24px',
      minH: '24px',
      p: '1',
      borderRadius: 'sm',
      _hover: { color: 'text' },
      _focusVisible: {
        outline: 'none',
        boxShadow: 'outline',
      },
    },
  },
});
