import { defineSlotRecipe } from '@pandacss/dev';

export const menu = defineSlotRecipe({
  className: 'menu',
  description: 'Disclosure menu using details/summary',
  slots: ['root', 'trigger', 'content', 'item'],
  base: {
    root: {
      display: 'inline-block',
      position: 'relative',
    },
    trigger: {
      listStyle: 'none',
      cursor: 'pointer',
      fontFamily: 'sans',
      fontWeight: 'medium',
      fontSize: 'sm',
      px: 3,
      py: 2,
      borderWidth: '1px',
      borderStyle: 'solid',
      borderColor: 'neutral.500',
      borderRadius: 'md',
      backgroundColor: 'neutral.800',
      color: 'text',
      _light: {
        backgroundColor: 'white',
        color: 'lightText',
        borderColor: 'neutral.400',
      },
      _focusVisible: {
        outline: 'none',
        boxShadow: 'outline',
      },
      '&::-webkit-details-marker': { display: 'none' },
      '&::marker': { content: '""' },
    },
    content: {
      position: 'absolute',
      zIndex: 20,
      mt: '1',
      minWidth: '10rem',
      p: '1',
      borderWidth: '1px',
      borderStyle: 'solid',
      borderColor: 'neutral.700',
      borderRadius: 'md',
      backgroundColor: 'neutral.800',
      boxShadow: 'elevated',
      _light: {
        backgroundColor: 'white',
        borderColor: 'border',
        boxShadow: 'md',
      },
    },
    item: {
      display: 'block',
      width: '100%',
      textAlign: 'left',
      appearance: 'none',
      border: 'none',
      background: 'transparent',
      color: 'text',
      fontFamily: 'sans',
      fontSize: 'sm',
      px: 3,
      py: 2,
      borderRadius: 'sm',
      cursor: 'pointer',
      _hover: { backgroundColor: 'neutral.700' },
      _light: {
        color: 'lightText',
        _hover: { backgroundColor: 'neutral.100' },
      },
      _focusVisible: {
        outline: 'none',
        boxShadow: 'outline',
      },
      _disabled: {
        opacity: 0.6,
        cursor: 'not-allowed',
      },
    },
  },
});
